DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS departments;

CREATE TABLE departments (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30) NOT NULL
);

CREATE TABLE roles (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  job_title VARCHAR(30) NOT NULL,
  dept_id INTEGER,
  salary INTEGER NOT NULL,
  CONSTRAINT fk_department FOREIGN KEY(dept_id) REFERENCES departments(id) ON DELETE SET NULL
)